version: "3.6"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    expose: 
      - "$JENKINS_PORT"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=$JENKINS_HOST,www.$JENKINS_HOST
      - VIRTUAL_PORT=$JENKINS_PORT
      - LETSENCRYPT_HOST=$JENKINS_HOST
      - LETSENCRYPT_EMAIL=$EMAIL
    networks:
      - nginx_frontend

networks:
  nginx_frontend:
    external: true

volumes:
  jenkins_home: