version: "3.6"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-ci
    expose: 
      - "$JENKINS_PORT"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=$JENKINS_HOST,www.$JENKINS_HOST
      - LETSENCRYPT_HOST=$JENKINS_HOST
      - LETSENCRYPT_EMAIL=$EMAIL
    networks:
      - nginx_frontend

networks:
  nginx_frontend:
    external: true

volumes:
  jenkins_home: